# coding: utf-8

# flake8: noqa
"""
    Agent Memory API

     A temporal-semantic memory system for AI agents that stores, retrieves, and reasons over memories.  ## Features  * **Batch Memory Storage**: Store multiple memories efficiently with automatic fact extraction * **Semantic Search**: Find relevant memories using natural language queries * **Fact Type Filtering**: Search across world facts, agent actions, and opinions separately * **Think Endpoint**: Generate contextual answers based on agent identity and memories * **Graph Visualization**: Interactive memory graph visualization * **Document Tracking**: Track and manage memory documents with upsert support  ## Architecture  The system uses: - **Temporal Links**: Connect memories that are close in time - **Semantic Links**: Connect semantically similar memories - **Entity Links**: Connect memories that mention the same entities - **Spreading Activation**: Intelligent traversal for memory retrieval         

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from hindsight_client_api.models.add_background_request import AddBackgroundRequest
from hindsight_client_api.models.agent_list_item import AgentListItem
from hindsight_client_api.models.agent_list_response import AgentListResponse
from hindsight_client_api.models.agent_profile_response import AgentProfileResponse
from hindsight_client_api.models.background_response import BackgroundResponse
from hindsight_client_api.models.batch_put_async_response import BatchPutAsyncResponse
from hindsight_client_api.models.batch_put_request import BatchPutRequest
from hindsight_client_api.models.batch_put_response import BatchPutResponse
from hindsight_client_api.models.create_agent_request import CreateAgentRequest
from hindsight_client_api.models.delete_response import DeleteResponse
from hindsight_client_api.models.document_response import DocumentResponse
from hindsight_client_api.models.graph_data_response import GraphDataResponse
from hindsight_client_api.models.http_validation_error import HTTPValidationError
from hindsight_client_api.models.list_documents_response import ListDocumentsResponse
from hindsight_client_api.models.list_memory_units_response import ListMemoryUnitsResponse
from hindsight_client_api.models.memory_item import MemoryItem
from hindsight_client_api.models.personality_traits import PersonalityTraits
from hindsight_client_api.models.search_request import SearchRequest
from hindsight_client_api.models.search_response import SearchResponse
from hindsight_client_api.models.search_result import SearchResult
from hindsight_client_api.models.think_fact import ThinkFact
from hindsight_client_api.models.think_request import ThinkRequest
from hindsight_client_api.models.think_response import ThinkResponse
from hindsight_client_api.models.update_personality_request import UpdatePersonalityRequest
from hindsight_client_api.models.validation_error import ValidationError
from hindsight_client_api.models.validation_error_loc_inner import ValidationErrorLocInner

