# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.10.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hindsight_client_api.models.consolidation_scope_pattern import ConsolidationScopePattern
from typing import Optional, Set
from typing_extensions import Self

class ConsolidationStrategySpec(BaseModel):
    """
    One `consolidation_strategies` entry: the rules it claims scopes with, and the observation settings those scopes use. Every setting is optional; unset ones come from the bank-wide values.
    """ # noqa: E501
    scopes: Optional[List[ConsolidationScopePattern]] = Field(default=None, description="Alternatives: the strategy claims a scope when any rule matches it")
    observations_mission: Optional[StrictStr] = None
    max_observations_per_scope: Optional[StrictInt] = None
    consolidation_source_facts_max_tokens: Optional[StrictInt] = None
    consolidation_source_facts_max_tokens_per_observation: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["scopes", "observations_mission", "max_observations_per_scope", "consolidation_source_facts_max_tokens", "consolidation_source_facts_max_tokens_per_observation"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConsolidationStrategySpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in scopes (list)
        _items = []
        if self.scopes:
            for _item_scopes in self.scopes:
                if _item_scopes:
                    _items.append(_item_scopes.to_dict())
            _dict['scopes'] = _items
        # set to None if observations_mission (nullable) is None
        # and model_fields_set contains the field
        if self.observations_mission is None and "observations_mission" in self.model_fields_set:
            _dict['observations_mission'] = None

        # set to None if max_observations_per_scope (nullable) is None
        # and model_fields_set contains the field
        if self.max_observations_per_scope is None and "max_observations_per_scope" in self.model_fields_set:
            _dict['max_observations_per_scope'] = None

        # set to None if consolidation_source_facts_max_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.consolidation_source_facts_max_tokens is None and "consolidation_source_facts_max_tokens" in self.model_fields_set:
            _dict['consolidation_source_facts_max_tokens'] = None

        # set to None if consolidation_source_facts_max_tokens_per_observation (nullable) is None
        # and model_fields_set contains the field
        if self.consolidation_source_facts_max_tokens_per_observation is None and "consolidation_source_facts_max_tokens_per_observation" in self.model_fields_set:
            _dict['consolidation_source_facts_max_tokens_per_observation'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConsolidationStrategySpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "scopes": [ConsolidationScopePattern.from_dict(_item) for _item in obj["scopes"]] if obj.get("scopes") is not None else None,
            "observations_mission": obj.get("observations_mission"),
            "max_observations_per_scope": obj.get("max_observations_per_scope"),
            "consolidation_source_facts_max_tokens": obj.get("consolidation_source_facts_max_tokens"),
            "consolidation_source_facts_max_tokens_per_observation": obj.get("consolidation_source_facts_max_tokens_per_observation")
        })
        return _obj


