# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.9.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from hindsight_client_api.models.file_content_block import FileContentBlock
from hindsight_client_api.models.image_content_block import ImageContentBlock
from hindsight_client_api.models.text_content_block import TextContentBlock
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

CONTENTANYOFINNER_ONE_OF_SCHEMAS = ["FileContentBlock", "ImageContentBlock", "TextContentBlock"]

class ContentAnyOfInner(BaseModel):
    """
    ContentAnyOfInner
    """
    # data type: TextContentBlock
    oneof_schema_1_validator: Optional[TextContentBlock] = None
    # data type: ImageContentBlock
    oneof_schema_2_validator: Optional[ImageContentBlock] = None
    # data type: FileContentBlock
    oneof_schema_3_validator: Optional[FileContentBlock] = None
    actual_instance: Optional[Union[FileContentBlock, ImageContentBlock, TextContentBlock]] = None
    one_of_schemas: Set[str] = { "FileContentBlock", "ImageContentBlock", "TextContentBlock" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ContentAnyOfInner.model_construct()
        error_messages = []
        match = 0
        # validate data type: TextContentBlock
        if not isinstance(v, TextContentBlock):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TextContentBlock`")
        else:
            match += 1
        # validate data type: ImageContentBlock
        if not isinstance(v, ImageContentBlock):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ImageContentBlock`")
        else:
            match += 1
        # validate data type: FileContentBlock
        if not isinstance(v, FileContentBlock):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FileContentBlock`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ContentAnyOfInner with oneOf schemas: FileContentBlock, ImageContentBlock, TextContentBlock. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ContentAnyOfInner with oneOf schemas: FileContentBlock, ImageContentBlock, TextContentBlock. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into TextContentBlock
        try:
            instance.actual_instance = TextContentBlock.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ImageContentBlock
        try:
            instance.actual_instance = ImageContentBlock.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FileContentBlock
        try:
            instance.actual_instance = FileContentBlock.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ContentAnyOfInner with oneOf schemas: FileContentBlock, ImageContentBlock, TextContentBlock. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ContentAnyOfInner with oneOf schemas: FileContentBlock, ImageContentBlock, TextContentBlock. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], FileContentBlock, ImageContentBlock, TextContentBlock]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


