# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.9.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class EntityGraphEdgeData(BaseModel):
    """
    The payload of one co-occurrence edge.
    """ # noqa: E501
    id: StrictStr = Field(description="Edge ID (``<source>-<target>``)")
    source: StrictStr = Field(description="Source entity ID")
    target: StrictStr = Field(description="Target entity ID")
    link_type: Optional[StrictStr] = Field(default='cooccurrence', description="Kind of relationship this edge represents", alias="linkType")
    weight: Optional[StrictInt] = Field(default=0, description="Number of co-occurrences between the two entities")
    color: Optional[StrictStr] = None
    line_style: Optional[StrictStr] = Field(default=None, alias="lineStyle")
    last_cooccurred: Optional[StrictStr] = Field(default=None, alias="lastCooccurred")
    __properties: ClassVar[List[str]] = ["id", "source", "target", "linkType", "weight", "color", "lineStyle", "lastCooccurred"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntityGraphEdgeData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if color (nullable) is None
        # and model_fields_set contains the field
        if self.color is None and "color" in self.model_fields_set:
            _dict['color'] = None

        # set to None if line_style (nullable) is None
        # and model_fields_set contains the field
        if self.line_style is None and "line_style" in self.model_fields_set:
            _dict['lineStyle'] = None

        # set to None if last_cooccurred (nullable) is None
        # and model_fields_set contains the field
        if self.last_cooccurred is None and "last_cooccurred" in self.model_fields_set:
            _dict['lastCooccurred'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntityGraphEdgeData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "source": obj.get("source"),
            "target": obj.get("target"),
            "linkType": obj.get("linkType") if obj.get("linkType") is not None else 'cooccurrence',
            "weight": obj.get("weight") if obj.get("weight") is not None else 0,
            "color": obj.get("color"),
            "lineStyle": obj.get("lineStyle"),
            "lastCooccurred": obj.get("lastCooccurred")
        })
        return _obj


