# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.9.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List
from hindsight_client_api.models.memory_graph_edge import MemoryGraphEdge
from hindsight_client_api.models.memory_graph_node import MemoryGraphNode
from hindsight_client_api.models.memory_graph_table_row import MemoryGraphTableRow
from typing import Optional, Set
from typing_extensions import Self

class GraphDataResponse(BaseModel):
    """
    Response model for graph data endpoint.
    """ # noqa: E501
    nodes: List[MemoryGraphNode]
    edges: List[MemoryGraphEdge]
    table_rows: List[MemoryGraphTableRow]
    total_units: StrictInt
    limit: StrictInt
    __properties: ClassVar[List[str]] = ["nodes", "edges", "table_rows", "total_units", "limit"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GraphDataResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in nodes (list)
        _items = []
        if self.nodes:
            for _item_nodes in self.nodes:
                if _item_nodes:
                    _items.append(_item_nodes.to_dict())
            _dict['nodes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in edges (list)
        _items = []
        if self.edges:
            for _item_edges in self.edges:
                if _item_edges:
                    _items.append(_item_edges.to_dict())
            _dict['edges'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in table_rows (list)
        _items = []
        if self.table_rows:
            for _item_table_rows in self.table_rows:
                if _item_table_rows:
                    _items.append(_item_table_rows.to_dict())
            _dict['table_rows'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GraphDataResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "nodes": [MemoryGraphNode.from_dict(_item) for _item in obj["nodes"]] if obj.get("nodes") is not None else None,
            "edges": [MemoryGraphEdge.from_dict(_item) for _item in obj["edges"]] if obj.get("edges") is not None else None,
            "table_rows": [MemoryGraphTableRow.from_dict(_item) for _item in obj["table_rows"]] if obj.get("table_rows") is not None else None,
            "total_units": obj.get("total_units"),
            "limit": obj.get("limit")
        })
        return _obj


