# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.9.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MemoryUnitListItem(BaseModel):
    """
    One row of the memory-unit listing.  Extra keys are allowed and passed through: the rows used to be an open object, and typing them must not drop a field an older or newer server also returns.
    """ # noqa: E501
    id: StrictStr = Field(description="Memory unit ID")
    text: Optional[StrictStr] = Field(default='', description="The fact text")
    context: Optional[StrictStr] = Field(default='', description="Context the memory was captured in")
    var_date: Optional[StrictStr] = Field(default='', description="Event date (ISO 8601), empty when unknown", alias="date")
    fact_type: Optional[StrictStr] = None
    document_id: Optional[StrictStr] = None
    mentioned_at: Optional[StrictStr] = None
    occurred_start: Optional[StrictStr] = None
    occurred_end: Optional[StrictStr] = None
    entities: Optional[StrictStr] = Field(default='', description="Comma-separated canonical entity names")
    chunk_id: Optional[StrictStr] = None
    proof_count: Optional[StrictInt] = Field(default=1, description="How many times the fact was independently seen")
    tags: Optional[List[StrictStr]] = Field(default=None, description="Tags on this memory unit")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Arbitrary metadata stored with the memory")
    consolidated_at: Optional[StrictStr] = None
    consolidation_failed_at: Optional[StrictStr] = None
    state: Optional[StrictStr] = Field(default='valid', description="Curation state: 'valid' or 'invalidated'")
    invalidation_reason: Optional[StrictStr] = None
    invalidated_at: Optional[StrictStr] = None
    edited_at: Optional[StrictStr] = None
    updated_at: Optional[StrictStr] = None
    source_memory_ids: Optional[List[StrictStr]] = Field(default=None, description="An observation's source facts; empty for a source fact")
    __properties: ClassVar[List[str]] = ["id", "text", "context", "date", "fact_type", "document_id", "mentioned_at", "occurred_start", "occurred_end", "entities", "chunk_id", "proof_count", "tags", "metadata", "consolidated_at", "consolidation_failed_at", "state", "invalidation_reason", "invalidated_at", "edited_at", "updated_at", "source_memory_ids"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MemoryUnitListItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if fact_type (nullable) is None
        # and model_fields_set contains the field
        if self.fact_type is None and "fact_type" in self.model_fields_set:
            _dict['fact_type'] = None

        # set to None if document_id (nullable) is None
        # and model_fields_set contains the field
        if self.document_id is None and "document_id" in self.model_fields_set:
            _dict['document_id'] = None

        # set to None if mentioned_at (nullable) is None
        # and model_fields_set contains the field
        if self.mentioned_at is None and "mentioned_at" in self.model_fields_set:
            _dict['mentioned_at'] = None

        # set to None if occurred_start (nullable) is None
        # and model_fields_set contains the field
        if self.occurred_start is None and "occurred_start" in self.model_fields_set:
            _dict['occurred_start'] = None

        # set to None if occurred_end (nullable) is None
        # and model_fields_set contains the field
        if self.occurred_end is None and "occurred_end" in self.model_fields_set:
            _dict['occurred_end'] = None

        # set to None if chunk_id (nullable) is None
        # and model_fields_set contains the field
        if self.chunk_id is None and "chunk_id" in self.model_fields_set:
            _dict['chunk_id'] = None

        # set to None if consolidated_at (nullable) is None
        # and model_fields_set contains the field
        if self.consolidated_at is None and "consolidated_at" in self.model_fields_set:
            _dict['consolidated_at'] = None

        # set to None if consolidation_failed_at (nullable) is None
        # and model_fields_set contains the field
        if self.consolidation_failed_at is None and "consolidation_failed_at" in self.model_fields_set:
            _dict['consolidation_failed_at'] = None

        # set to None if invalidation_reason (nullable) is None
        # and model_fields_set contains the field
        if self.invalidation_reason is None and "invalidation_reason" in self.model_fields_set:
            _dict['invalidation_reason'] = None

        # set to None if invalidated_at (nullable) is None
        # and model_fields_set contains the field
        if self.invalidated_at is None and "invalidated_at" in self.model_fields_set:
            _dict['invalidated_at'] = None

        # set to None if edited_at (nullable) is None
        # and model_fields_set contains the field
        if self.edited_at is None and "edited_at" in self.model_fields_set:
            _dict['edited_at'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MemoryUnitListItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "text": obj.get("text") if obj.get("text") is not None else '',
            "context": obj.get("context") if obj.get("context") is not None else '',
            "date": obj.get("date") if obj.get("date") is not None else '',
            "fact_type": obj.get("fact_type"),
            "document_id": obj.get("document_id"),
            "mentioned_at": obj.get("mentioned_at"),
            "occurred_start": obj.get("occurred_start"),
            "occurred_end": obj.get("occurred_end"),
            "entities": obj.get("entities") if obj.get("entities") is not None else '',
            "chunk_id": obj.get("chunk_id"),
            "proof_count": obj.get("proof_count") if obj.get("proof_count") is not None else 1,
            "tags": obj.get("tags"),
            "metadata": obj.get("metadata"),
            "consolidated_at": obj.get("consolidated_at"),
            "consolidation_failed_at": obj.get("consolidation_failed_at"),
            "state": obj.get("state") if obj.get("state") is not None else 'valid',
            "invalidation_reason": obj.get("invalidation_reason"),
            "invalidated_at": obj.get("invalidated_at"),
            "edited_at": obj.get("edited_at"),
            "updated_at": obj.get("updated_at"),
            "source_memory_ids": obj.get("source_memory_ids")
        })
        return _obj


