# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.9.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MentalModelRetraction(BaseModel):
    """
    Facts the document cited that no longer exist, and what was done about them.  A retraction is the one refresh input that is *invisible* in every other report: the fact is gone from the bank, so it appears in no recall, no tool call, and no supporting-fact list. Without this, a refresh that quietly deleted a paragraph — or quietly declined to — leaves no evidence of why.
    """ # noqa: E501
    fact_ids: Optional[List[StrictStr]] = Field(default=None, description="Ids the document's based_on cites that no longer exist in the bank.")
    fact_texts: Optional[List[StrictStr]] = Field(default=None, description="What those facts said, as the document recorded them. The rows themselves are gone — an observation swept away with its source keeps no history — so this copy is the only surviving record.")
    applied: StrictBool = Field(description="Whether the pass that removes them ran to completion (zero edits still counts).")
    deferred_reason: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["fact_ids", "fact_texts", "applied", "deferred_reason"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MentalModelRetraction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if deferred_reason (nullable) is None
        # and model_fields_set contains the field
        if self.deferred_reason is None and "deferred_reason" in self.model_fields_set:
            _dict['deferred_reason'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MentalModelRetraction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fact_ids": obj.get("fact_ids"),
            "fact_texts": obj.get("fact_texts"),
            "applied": obj.get("applied"),
            "deferred_reason": obj.get("deferred_reason")
        })
        return _obj


