// Code generated by ogen, DO NOT EDIT.

package ogenapi

// AddBankBackgroundParams is parameters of add_bank_background operation.
type AddBankBackgroundParams struct {
	BankID string
}

// CancelOperationParams is parameters of cancel_operation operation.
type CancelOperationParams struct {
	BankID      string
	OperationID string
}

// ClearBankMemoriesParams is parameters of clear_bank_memories operation.
type ClearBankMemoriesParams struct {
	BankID string
	// Optional fact type filter (world, experience, opinion).
	Type OptString `json:",omitempty,omitzero"`
}

// ClearObservationsParams is parameters of clear_observations operation.
type ClearObservationsParams struct {
	BankID string
}

// CreateDirectiveParams is parameters of create_directive operation.
type CreateDirectiveParams struct {
	BankID string
}

// CreateMentalModelParams is parameters of create_mental_model operation.
type CreateMentalModelParams struct {
	BankID string
}

// CreateOrUpdateBankParams is parameters of create_or_update_bank operation.
type CreateOrUpdateBankParams struct {
	BankID string
}

// DeleteBankParams is parameters of delete_bank operation.
type DeleteBankParams struct {
	BankID string
}

// DeleteDirectiveParams is parameters of delete_directive operation.
type DeleteDirectiveParams struct {
	BankID      string
	DirectiveID string
}

// DeleteDocumentParams is parameters of delete_document operation.
type DeleteDocumentParams struct {
	BankID     string
	DocumentID string
}

// DeleteMentalModelParams is parameters of delete_mental_model operation.
type DeleteMentalModelParams struct {
	BankID        string
	MentalModelID string
}

// GetAgentStatsParams is parameters of get_agent_stats operation.
type GetAgentStatsParams struct {
	BankID string
}

// GetBankConfigParams is parameters of get_bank_config operation.
type GetBankConfigParams struct {
	BankID string
}

// GetBankProfileParams is parameters of get_bank_profile operation.
type GetBankProfileParams struct {
	BankID string
}

// GetChunkParams is parameters of get_chunk operation.
type GetChunkParams struct {
	ChunkID string
}

// GetDirectiveParams is parameters of get_directive operation.
type GetDirectiveParams struct {
	BankID      string
	DirectiveID string
}

// GetDocumentParams is parameters of get_document operation.
type GetDocumentParams struct {
	BankID     string
	DocumentID string
}

// GetEntityParams is parameters of get_entity operation.
type GetEntityParams struct {
	BankID   string
	EntityID string
}

// GetGraphParams is parameters of get_graph operation.
type GetGraphParams struct {
	BankID string
	Type   OptString `json:",omitempty,omitzero"`
	Limit  OptInt    `json:",omitempty,omitzero"`
}

// GetMemoryParams is parameters of get_memory operation.
type GetMemoryParams struct {
	BankID   string
	MemoryID string
}

// GetMentalModelParams is parameters of get_mental_model operation.
type GetMentalModelParams struct {
	BankID        string
	MentalModelID string
}

// GetOperationStatusParams is parameters of get_operation_status operation.
type GetOperationStatusParams struct {
	BankID      string
	OperationID string
}

// ListDirectivesParams is parameters of list_directives operation.
type ListDirectivesParams struct {
	BankID string
	// Filter by tags.
	Tags []string `json:",omitempty"`
	// How to match tags.
	TagsMatch OptListDirectivesTagsMatch `json:",omitempty,omitzero"`
	// Only return active directives.
	ActiveOnly OptBool `json:",omitempty,omitzero"`
	Limit      OptInt  `json:",omitempty,omitzero"`
	Offset     OptInt  `json:",omitempty,omitzero"`
}

// ListDocumentsParams is parameters of list_documents operation.
type ListDocumentsParams struct {
	BankID string
	Q      OptString `json:",omitempty,omitzero"`
	Limit  OptInt    `json:",omitempty,omitzero"`
	Offset OptInt    `json:",omitempty,omitzero"`
}

// ListEntitiesParams is parameters of list_entities operation.
type ListEntitiesParams struct {
	BankID string
	// Maximum number of entities to return.
	Limit OptInt `json:",omitempty,omitzero"`
	// Offset for pagination.
	Offset OptInt `json:",omitempty,omitzero"`
}

// ListMemoriesParams is parameters of list_memories operation.
type ListMemoriesParams struct {
	BankID string
	Type   OptString `json:",omitempty,omitzero"`
	Q      OptString `json:",omitempty,omitzero"`
	Limit  OptInt    `json:",omitempty,omitzero"`
	Offset OptInt    `json:",omitempty,omitzero"`
}

// ListMentalModelsParams is parameters of list_mental_models operation.
type ListMentalModelsParams struct {
	BankID string
	// Filter by tags.
	Tags []string `json:",omitempty"`
	// How to match tags.
	TagsMatch OptListMentalModelsTagsMatch `json:",omitempty,omitzero"`
	Limit     OptInt                       `json:",omitempty,omitzero"`
	Offset    OptInt                       `json:",omitempty,omitzero"`
}

// ListOperationsParams is parameters of list_operations operation.
type ListOperationsParams struct {
	BankID string
	// Filter by status: pending, completed, or failed.
	Status OptString `json:",omitempty,omitzero"`
	// Maximum number of operations to return.
	Limit OptInt `json:",omitempty,omitzero"`
	// Number of operations to skip.
	Offset OptInt `json:",omitempty,omitzero"`
}

// ListTagsParams is parameters of list_tags operation.
type ListTagsParams struct {
	BankID string
	// Wildcard pattern to filter tags (e.g., 'user:*' for user:alice, '*-admin' for role-admin). Use '*'
	// as wildcard. Case-insensitive.
	Q OptString `json:",omitempty,omitzero"`
	// Maximum number of tags to return.
	Limit OptInt `json:",omitempty,omitzero"`
	// Offset for pagination.
	Offset OptInt `json:",omitempty,omitzero"`
}

// RecallMemoriesParams is parameters of recall_memories operation.
type RecallMemoriesParams struct {
	BankID string
}

// ReflectParams is parameters of reflect operation.
type ReflectParams struct {
	BankID string
}

// RefreshMentalModelParams is parameters of refresh_mental_model operation.
type RefreshMentalModelParams struct {
	BankID        string
	MentalModelID string
}

// RegenerateEntityObservationsParams is parameters of regenerate_entity_observations operation.
type RegenerateEntityObservationsParams struct {
	BankID   string
	EntityID string
}

// ResetBankConfigParams is parameters of reset_bank_config operation.
type ResetBankConfigParams struct {
	BankID string
}

// RetainMemoriesParams is parameters of retain_memories operation.
type RetainMemoriesParams struct {
	BankID string
}

// TriggerConsolidationParams is parameters of trigger_consolidation operation.
type TriggerConsolidationParams struct {
	BankID string
}

// UpdateBankParams is parameters of update_bank operation.
type UpdateBankParams struct {
	BankID string
}

// UpdateBankConfigParams is parameters of update_bank_config operation.
type UpdateBankConfigParams struct {
	BankID string
}

// UpdateBankDispositionParams is parameters of update_bank_disposition operation.
type UpdateBankDispositionParams struct {
	BankID string
}

// UpdateDirectiveParams is parameters of update_directive operation.
type UpdateDirectiveParams struct {
	BankID      string
	DirectiveID string
}

// UpdateMentalModelParams is parameters of update_mental_model operation.
type UpdateMentalModelParams struct {
	BankID        string
	MentalModelID string
}
