# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.10.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictBytes, StrictStr
from typing import List, Optional, Tuple, Union
from typing_extensions import Annotated
from hindsight_client_api.models.bank_transfer_submit_response import BankTransferSubmitResponse

from hindsight_client_api.api_client import ApiClient, RequestSerialized
from hindsight_client_api.api_response import ApiResponse
from hindsight_client_api.rest import RESTResponseType


class BankTransferApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    async def clone_bank(
        self,
        bank_id: StrictStr,
        target_bank_id: Annotated[StrictStr, Field(description="Bank to create; must not already exist")],
        include_data: Annotated[Optional[StrictBool], Field(description="Copy the memories, what backs them, and the mental models and knowledge pages synthesized from them")] = None,
        include_bank_config: Annotated[Optional[StrictBool], Field(description="Copy the bank's config overrides, directives and webhooks")] = None,
        include_history: Annotated[Optional[StrictBool], Field(description="Copy audit_log and llm_requests")] = None,
        authorization: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> BankTransferSubmitResponse:
        """Clone a bank (async)

        Copy this bank into a new one, in a single call. The clone starts with the source's memories as they are at clone time and evolves independently from then on: later retains, consolidation and edits on either bank leave the other alone.  This is the export and import above run back to back on this instance, so nothing is re-extracted and no LLM is called — facts are re-embedded and entities re-resolved, exactly as a restore does. The same three flags choose what the clone inherits: include_data (documents, facts, observations, attachments, the curation archive, the operations log, and the mental models and knowledge pages synthesized from them), include_bank_config (the bank's config overrides, directives and **webhooks**) and include_history (audit_log, llm_requests).  Note the webhooks: they travel with the bank's configuration, so a clone made with the default flags will call the source's webhook endpoints. Pass include_bank_config=false, or delete them on the clone, when they point at a per-bank consumer.  target_bank_id must not already exist. Returns an operation_id, recorded against the source bank (the target does not exist yet); poll GET /v1/default/banks/{bank_id}/operations/{operation_id} for status and the per-component counts.

        :param bank_id: (required)
        :type bank_id: str
        :param target_bank_id: Bank to create; must not already exist (required)
        :type target_bank_id: str
        :param include_data: Copy the memories, what backs them, and the mental models and knowledge pages synthesized from them
        :type include_data: bool
        :param include_bank_config: Copy the bank's config overrides, directives and webhooks
        :type include_bank_config: bool
        :param include_history: Copy audit_log and llm_requests
        :type include_history: bool
        :param authorization:
        :type authorization: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._clone_bank_serialize(
            bank_id=bank_id,
            target_bank_id=target_bank_id,
            include_data=include_data,
            include_bank_config=include_bank_config,
            include_history=include_history,
            authorization=authorization,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '202': "BankTransferSubmitResponse",
            '404': None,
            '422': "HTTPValidationError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def clone_bank_with_http_info(
        self,
        bank_id: StrictStr,
        target_bank_id: Annotated[StrictStr, Field(description="Bank to create; must not already exist")],
        include_data: Annotated[Optional[StrictBool], Field(description="Copy the memories, what backs them, and the mental models and knowledge pages synthesized from them")] = None,
        include_bank_config: Annotated[Optional[StrictBool], Field(description="Copy the bank's config overrides, directives and webhooks")] = None,
        include_history: Annotated[Optional[StrictBool], Field(description="Copy audit_log and llm_requests")] = None,
        authorization: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[BankTransferSubmitResponse]:
        """Clone a bank (async)

        Copy this bank into a new one, in a single call. The clone starts with the source's memories as they are at clone time and evolves independently from then on: later retains, consolidation and edits on either bank leave the other alone.  This is the export and import above run back to back on this instance, so nothing is re-extracted and no LLM is called — facts are re-embedded and entities re-resolved, exactly as a restore does. The same three flags choose what the clone inherits: include_data (documents, facts, observations, attachments, the curation archive, the operations log, and the mental models and knowledge pages synthesized from them), include_bank_config (the bank's config overrides, directives and **webhooks**) and include_history (audit_log, llm_requests).  Note the webhooks: they travel with the bank's configuration, so a clone made with the default flags will call the source's webhook endpoints. Pass include_bank_config=false, or delete them on the clone, when they point at a per-bank consumer.  target_bank_id must not already exist. Returns an operation_id, recorded against the source bank (the target does not exist yet); poll GET /v1/default/banks/{bank_id}/operations/{operation_id} for status and the per-component counts.

        :param bank_id: (required)
        :type bank_id: str
        :param target_bank_id: Bank to create; must not already exist (required)
        :type target_bank_id: str
        :param include_data: Copy the memories, what backs them, and the mental models and knowledge pages synthesized from them
        :type include_data: bool
        :param include_bank_config: Copy the bank's config overrides, directives and webhooks
        :type include_bank_config: bool
        :param include_history: Copy audit_log and llm_requests
        :type include_history: bool
        :param authorization:
        :type authorization: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._clone_bank_serialize(
            bank_id=bank_id,
            target_bank_id=target_bank_id,
            include_data=include_data,
            include_bank_config=include_bank_config,
            include_history=include_history,
            authorization=authorization,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '202': "BankTransferSubmitResponse",
            '404': None,
            '422': "HTTPValidationError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def clone_bank_without_preload_content(
        self,
        bank_id: StrictStr,
        target_bank_id: Annotated[StrictStr, Field(description="Bank to create; must not already exist")],
        include_data: Annotated[Optional[StrictBool], Field(description="Copy the memories, what backs them, and the mental models and knowledge pages synthesized from them")] = None,
        include_bank_config: Annotated[Optional[StrictBool], Field(description="Copy the bank's config overrides, directives and webhooks")] = None,
        include_history: Annotated[Optional[StrictBool], Field(description="Copy audit_log and llm_requests")] = None,
        authorization: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Clone a bank (async)

        Copy this bank into a new one, in a single call. The clone starts with the source's memories as they are at clone time and evolves independently from then on: later retains, consolidation and edits on either bank leave the other alone.  This is the export and import above run back to back on this instance, so nothing is re-extracted and no LLM is called — facts are re-embedded and entities re-resolved, exactly as a restore does. The same three flags choose what the clone inherits: include_data (documents, facts, observations, attachments, the curation archive, the operations log, and the mental models and knowledge pages synthesized from them), include_bank_config (the bank's config overrides, directives and **webhooks**) and include_history (audit_log, llm_requests).  Note the webhooks: they travel with the bank's configuration, so a clone made with the default flags will call the source's webhook endpoints. Pass include_bank_config=false, or delete them on the clone, when they point at a per-bank consumer.  target_bank_id must not already exist. Returns an operation_id, recorded against the source bank (the target does not exist yet); poll GET /v1/default/banks/{bank_id}/operations/{operation_id} for status and the per-component counts.

        :param bank_id: (required)
        :type bank_id: str
        :param target_bank_id: Bank to create; must not already exist (required)
        :type target_bank_id: str
        :param include_data: Copy the memories, what backs them, and the mental models and knowledge pages synthesized from them
        :type include_data: bool
        :param include_bank_config: Copy the bank's config overrides, directives and webhooks
        :type include_bank_config: bool
        :param include_history: Copy audit_log and llm_requests
        :type include_history: bool
        :param authorization:
        :type authorization: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._clone_bank_serialize(
            bank_id=bank_id,
            target_bank_id=target_bank_id,
            include_data=include_data,
            include_bank_config=include_bank_config,
            include_history=include_history,
            authorization=authorization,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '202': "BankTransferSubmitResponse",
            '404': None,
            '422': "HTTPValidationError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _clone_bank_serialize(
        self,
        bank_id,
        target_bank_id,
        include_data,
        include_bank_config,
        include_history,
        authorization,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if bank_id is not None:
            _path_params['bank_id'] = bank_id
        # process the query parameters
        if target_bank_id is not None:
            
            _query_params.append(('target_bank_id', target_bank_id))
            
        if include_data is not None:
            
            _query_params.append(('include_data', include_data))
            
        if include_bank_config is not None:
            
            _query_params.append(('include_bank_config', include_bank_config))
            
        if include_history is not None:
            
            _query_params.append(('include_history', include_history))
            
        # process the header parameters
        if authorization is not None:
            _header_params['authorization'] = authorization
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/v1/default/banks/{bank_id}/clone',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    async def export_bank_transfer(
        self,
        bank_id: StrictStr,
        include_data: Annotated[Optional[StrictBool], Field(description="Carry the memories and everything backing them")] = None,
        include_bank_config: Annotated[Optional[StrictBool], Field(description="Carry the bank's config overrides, directives and webhooks")] = None,
        include_history: Annotated[Optional[StrictBool], Field(description="Carry audit_log and llm_requests")] = None,
        document_id: Annotated[Optional[List[StrictStr]], Field(description="Document id(s); omit for the whole bank")] = None,
        authorization: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> BankTransferSubmitResponse:
        """Export a bank (async)

        Submit an async export of a bank as a transfer ZIP archive. Three flags choose what the archive carries: include_data (documents, facts, observations, attachments and their bytes, the curation archive, the operations log and the maintenance queues), include_bank_config (bank config, mental models and their history, knowledge pages), include_bank_config (the bank's config overrides, directives and webhooks) and include_history (audit_log, llm_requests). Embeddings and database ids are never carried — importing re-embeds with the target bank's model and re-resolves entities, so an archive moves between instances configured with different embedding models. Returns an operation_id; poll GET /v1/default/banks/{bank_id}/operations/{operation_id}, then fetch the archive from the download_url in its result_metadata. Pass document_id to export specific documents instead of the whole bank (a document subset carries no bank-level sections).

        :param bank_id: (required)
        :type bank_id: str
        :param include_data: Carry the memories and everything backing them
        :type include_data: bool
        :param include_bank_config: Carry the bank's config overrides, directives and webhooks
        :type include_bank_config: bool
        :param include_history: Carry audit_log and llm_requests
        :type include_history: bool
        :param document_id: Document id(s); omit for the whole bank
        :type document_id: List[str]
        :param authorization:
        :type authorization: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._export_bank_transfer_serialize(
            bank_id=bank_id,
            include_data=include_data,
            include_bank_config=include_bank_config,
            include_history=include_history,
            document_id=document_id,
            authorization=authorization,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '202': "BankTransferSubmitResponse",
            '404': None,
            '422': "HTTPValidationError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def export_bank_transfer_with_http_info(
        self,
        bank_id: StrictStr,
        include_data: Annotated[Optional[StrictBool], Field(description="Carry the memories and everything backing them")] = None,
        include_bank_config: Annotated[Optional[StrictBool], Field(description="Carry the bank's config overrides, directives and webhooks")] = None,
        include_history: Annotated[Optional[StrictBool], Field(description="Carry audit_log and llm_requests")] = None,
        document_id: Annotated[Optional[List[StrictStr]], Field(description="Document id(s); omit for the whole bank")] = None,
        authorization: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[BankTransferSubmitResponse]:
        """Export a bank (async)

        Submit an async export of a bank as a transfer ZIP archive. Three flags choose what the archive carries: include_data (documents, facts, observations, attachments and their bytes, the curation archive, the operations log and the maintenance queues), include_bank_config (bank config, mental models and their history, knowledge pages), include_bank_config (the bank's config overrides, directives and webhooks) and include_history (audit_log, llm_requests). Embeddings and database ids are never carried — importing re-embeds with the target bank's model and re-resolves entities, so an archive moves between instances configured with different embedding models. Returns an operation_id; poll GET /v1/default/banks/{bank_id}/operations/{operation_id}, then fetch the archive from the download_url in its result_metadata. Pass document_id to export specific documents instead of the whole bank (a document subset carries no bank-level sections).

        :param bank_id: (required)
        :type bank_id: str
        :param include_data: Carry the memories and everything backing them
        :type include_data: bool
        :param include_bank_config: Carry the bank's config overrides, directives and webhooks
        :type include_bank_config: bool
        :param include_history: Carry audit_log and llm_requests
        :type include_history: bool
        :param document_id: Document id(s); omit for the whole bank
        :type document_id: List[str]
        :param authorization:
        :type authorization: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._export_bank_transfer_serialize(
            bank_id=bank_id,
            include_data=include_data,
            include_bank_config=include_bank_config,
            include_history=include_history,
            document_id=document_id,
            authorization=authorization,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '202': "BankTransferSubmitResponse",
            '404': None,
            '422': "HTTPValidationError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def export_bank_transfer_without_preload_content(
        self,
        bank_id: StrictStr,
        include_data: Annotated[Optional[StrictBool], Field(description="Carry the memories and everything backing them")] = None,
        include_bank_config: Annotated[Optional[StrictBool], Field(description="Carry the bank's config overrides, directives and webhooks")] = None,
        include_history: Annotated[Optional[StrictBool], Field(description="Carry audit_log and llm_requests")] = None,
        document_id: Annotated[Optional[List[StrictStr]], Field(description="Document id(s); omit for the whole bank")] = None,
        authorization: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Export a bank (async)

        Submit an async export of a bank as a transfer ZIP archive. Three flags choose what the archive carries: include_data (documents, facts, observations, attachments and their bytes, the curation archive, the operations log and the maintenance queues), include_bank_config (bank config, mental models and their history, knowledge pages), include_bank_config (the bank's config overrides, directives and webhooks) and include_history (audit_log, llm_requests). Embeddings and database ids are never carried — importing re-embeds with the target bank's model and re-resolves entities, so an archive moves between instances configured with different embedding models. Returns an operation_id; poll GET /v1/default/banks/{bank_id}/operations/{operation_id}, then fetch the archive from the download_url in its result_metadata. Pass document_id to export specific documents instead of the whole bank (a document subset carries no bank-level sections).

        :param bank_id: (required)
        :type bank_id: str
        :param include_data: Carry the memories and everything backing them
        :type include_data: bool
        :param include_bank_config: Carry the bank's config overrides, directives and webhooks
        :type include_bank_config: bool
        :param include_history: Carry audit_log and llm_requests
        :type include_history: bool
        :param document_id: Document id(s); omit for the whole bank
        :type document_id: List[str]
        :param authorization:
        :type authorization: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._export_bank_transfer_serialize(
            bank_id=bank_id,
            include_data=include_data,
            include_bank_config=include_bank_config,
            include_history=include_history,
            document_id=document_id,
            authorization=authorization,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '202': "BankTransferSubmitResponse",
            '404': None,
            '422': "HTTPValidationError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _export_bank_transfer_serialize(
        self,
        bank_id,
        include_data,
        include_bank_config,
        include_history,
        document_id,
        authorization,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'document_id': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if bank_id is not None:
            _path_params['bank_id'] = bank_id
        # process the query parameters
        if include_data is not None:
            
            _query_params.append(('include_data', include_data))
            
        if include_bank_config is not None:
            
            _query_params.append(('include_bank_config', include_bank_config))
            
        if include_history is not None:
            
            _query_params.append(('include_history', include_history))
            
        if document_id is not None:
            
            _query_params.append(('document_id', document_id))
            
        # process the header parameters
        if authorization is not None:
            _header_params['authorization'] = authorization
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/v1/default/banks/{bank_id}/transfer/export',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    async def import_bank_transfer(
        self,
        bank_id: StrictStr,
        file: Annotated[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]], Field(description="Transfer ZIP archive")],
        mode: Annotated[Optional[StrictStr], Field(description="restore (into a fresh bank) | merge (into this bank)")] = None,
        target_bank_id: Annotated[Optional[StrictStr], Field(description="restore mode: the bank to create; defaults to the archive's source bank")] = None,
        document_conflict: Annotated[Optional[StrictStr], Field(description="merge mode: skip | replace | new-id")] = None,
        include_data: Annotated[Optional[StrictBool], Field(description="restore mode: carry the memories and everything backing them (default true)")] = None,
        include_bank_config: Annotated[Optional[StrictBool], Field(description="restore mode: restore the bank's config overrides, directives and webhooks (default true)")] = None,
        include_history: Annotated[Optional[StrictBool], Field(description="restore mode: carry audit_log and llm_requests (default false)")] = None,
        authorization: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> BankTransferSubmitResponse:
        """Import a bank (async)

        Submit a transfer archive (produced by the export endpoint) for import. Runs as a background operation: facts are re-embedded with the target bank's embedding model and entities are re-resolved — no LLM extraction, so the import costs no tokens and invents no new facts.  Two modes. `restore` (default) writes a whole bank into target_bank_id, which must NOT already exist — it restores a bank rather than merging into one, and is how a bank is moved between instances or copied under a new id. `merge` folds an archive's documents into this bank, with document_conflict deciding what happens to ids that already exist (skip, replace, new-id).  The include flags narrow what is restored to a subset of what the archive holds; they cannot add what the producer did not export. Returns an operation_id; poll GET /v1/default/banks/{bank_id}/operations/{operation_id} for status and per-component counts. The operation is recorded against {bank_id} even in restore mode, because the target bank does not exist yet.

        :param bank_id: (required)
        :type bank_id: str
        :param file: Transfer ZIP archive (required)
        :type file: bytearray
        :param mode: restore (into a fresh bank) | merge (into this bank)
        :type mode: str
        :param target_bank_id: restore mode: the bank to create; defaults to the archive's source bank
        :type target_bank_id: str
        :param document_conflict: merge mode: skip | replace | new-id
        :type document_conflict: str
        :param include_data: restore mode: carry the memories and everything backing them (default true)
        :type include_data: bool
        :param include_bank_config: restore mode: restore the bank's config overrides, directives and webhooks (default true)
        :type include_bank_config: bool
        :param include_history: restore mode: carry audit_log and llm_requests (default false)
        :type include_history: bool
        :param authorization:
        :type authorization: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._import_bank_transfer_serialize(
            bank_id=bank_id,
            file=file,
            mode=mode,
            target_bank_id=target_bank_id,
            document_conflict=document_conflict,
            include_data=include_data,
            include_bank_config=include_bank_config,
            include_history=include_history,
            authorization=authorization,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '202': "BankTransferSubmitResponse",
            '422': "HTTPValidationError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def import_bank_transfer_with_http_info(
        self,
        bank_id: StrictStr,
        file: Annotated[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]], Field(description="Transfer ZIP archive")],
        mode: Annotated[Optional[StrictStr], Field(description="restore (into a fresh bank) | merge (into this bank)")] = None,
        target_bank_id: Annotated[Optional[StrictStr], Field(description="restore mode: the bank to create; defaults to the archive's source bank")] = None,
        document_conflict: Annotated[Optional[StrictStr], Field(description="merge mode: skip | replace | new-id")] = None,
        include_data: Annotated[Optional[StrictBool], Field(description="restore mode: carry the memories and everything backing them (default true)")] = None,
        include_bank_config: Annotated[Optional[StrictBool], Field(description="restore mode: restore the bank's config overrides, directives and webhooks (default true)")] = None,
        include_history: Annotated[Optional[StrictBool], Field(description="restore mode: carry audit_log and llm_requests (default false)")] = None,
        authorization: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[BankTransferSubmitResponse]:
        """Import a bank (async)

        Submit a transfer archive (produced by the export endpoint) for import. Runs as a background operation: facts are re-embedded with the target bank's embedding model and entities are re-resolved — no LLM extraction, so the import costs no tokens and invents no new facts.  Two modes. `restore` (default) writes a whole bank into target_bank_id, which must NOT already exist — it restores a bank rather than merging into one, and is how a bank is moved between instances or copied under a new id. `merge` folds an archive's documents into this bank, with document_conflict deciding what happens to ids that already exist (skip, replace, new-id).  The include flags narrow what is restored to a subset of what the archive holds; they cannot add what the producer did not export. Returns an operation_id; poll GET /v1/default/banks/{bank_id}/operations/{operation_id} for status and per-component counts. The operation is recorded against {bank_id} even in restore mode, because the target bank does not exist yet.

        :param bank_id: (required)
        :type bank_id: str
        :param file: Transfer ZIP archive (required)
        :type file: bytearray
        :param mode: restore (into a fresh bank) | merge (into this bank)
        :type mode: str
        :param target_bank_id: restore mode: the bank to create; defaults to the archive's source bank
        :type target_bank_id: str
        :param document_conflict: merge mode: skip | replace | new-id
        :type document_conflict: str
        :param include_data: restore mode: carry the memories and everything backing them (default true)
        :type include_data: bool
        :param include_bank_config: restore mode: restore the bank's config overrides, directives and webhooks (default true)
        :type include_bank_config: bool
        :param include_history: restore mode: carry audit_log and llm_requests (default false)
        :type include_history: bool
        :param authorization:
        :type authorization: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._import_bank_transfer_serialize(
            bank_id=bank_id,
            file=file,
            mode=mode,
            target_bank_id=target_bank_id,
            document_conflict=document_conflict,
            include_data=include_data,
            include_bank_config=include_bank_config,
            include_history=include_history,
            authorization=authorization,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '202': "BankTransferSubmitResponse",
            '422': "HTTPValidationError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def import_bank_transfer_without_preload_content(
        self,
        bank_id: StrictStr,
        file: Annotated[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]], Field(description="Transfer ZIP archive")],
        mode: Annotated[Optional[StrictStr], Field(description="restore (into a fresh bank) | merge (into this bank)")] = None,
        target_bank_id: Annotated[Optional[StrictStr], Field(description="restore mode: the bank to create; defaults to the archive's source bank")] = None,
        document_conflict: Annotated[Optional[StrictStr], Field(description="merge mode: skip | replace | new-id")] = None,
        include_data: Annotated[Optional[StrictBool], Field(description="restore mode: carry the memories and everything backing them (default true)")] = None,
        include_bank_config: Annotated[Optional[StrictBool], Field(description="restore mode: restore the bank's config overrides, directives and webhooks (default true)")] = None,
        include_history: Annotated[Optional[StrictBool], Field(description="restore mode: carry audit_log and llm_requests (default false)")] = None,
        authorization: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Import a bank (async)

        Submit a transfer archive (produced by the export endpoint) for import. Runs as a background operation: facts are re-embedded with the target bank's embedding model and entities are re-resolved — no LLM extraction, so the import costs no tokens and invents no new facts.  Two modes. `restore` (default) writes a whole bank into target_bank_id, which must NOT already exist — it restores a bank rather than merging into one, and is how a bank is moved between instances or copied under a new id. `merge` folds an archive's documents into this bank, with document_conflict deciding what happens to ids that already exist (skip, replace, new-id).  The include flags narrow what is restored to a subset of what the archive holds; they cannot add what the producer did not export. Returns an operation_id; poll GET /v1/default/banks/{bank_id}/operations/{operation_id} for status and per-component counts. The operation is recorded against {bank_id} even in restore mode, because the target bank does not exist yet.

        :param bank_id: (required)
        :type bank_id: str
        :param file: Transfer ZIP archive (required)
        :type file: bytearray
        :param mode: restore (into a fresh bank) | merge (into this bank)
        :type mode: str
        :param target_bank_id: restore mode: the bank to create; defaults to the archive's source bank
        :type target_bank_id: str
        :param document_conflict: merge mode: skip | replace | new-id
        :type document_conflict: str
        :param include_data: restore mode: carry the memories and everything backing them (default true)
        :type include_data: bool
        :param include_bank_config: restore mode: restore the bank's config overrides, directives and webhooks (default true)
        :type include_bank_config: bool
        :param include_history: restore mode: carry audit_log and llm_requests (default false)
        :type include_history: bool
        :param authorization:
        :type authorization: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._import_bank_transfer_serialize(
            bank_id=bank_id,
            file=file,
            mode=mode,
            target_bank_id=target_bank_id,
            document_conflict=document_conflict,
            include_data=include_data,
            include_bank_config=include_bank_config,
            include_history=include_history,
            authorization=authorization,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '202': "BankTransferSubmitResponse",
            '422': "HTTPValidationError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _import_bank_transfer_serialize(
        self,
        bank_id,
        file,
        mode,
        target_bank_id,
        document_conflict,
        include_data,
        include_bank_config,
        include_history,
        authorization,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if bank_id is not None:
            _path_params['bank_id'] = bank_id
        # process the query parameters
        if mode is not None:
            
            _query_params.append(('mode', mode))
            
        if target_bank_id is not None:
            
            _query_params.append(('target_bank_id', target_bank_id))
            
        if document_conflict is not None:
            
            _query_params.append(('document_conflict', document_conflict))
            
        if include_data is not None:
            
            _query_params.append(('include_data', include_data))
            
        if include_bank_config is not None:
            
            _query_params.append(('include_bank_config', include_bank_config))
            
        if include_history is not None:
            
            _query_params.append(('include_history', include_history))
            
        # process the header parameters
        if authorization is not None:
            _header_params['authorization'] = authorization
        # process the form parameters
        if file is not None:
            _files['file'] = file
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'multipart/form-data'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/v1/default/banks/{bank_id}/transfer/import',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


