/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetBankAliasPrimaryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetBankAliasPrimaryRequest{}

// SetBankAliasPrimaryRequest Request model for showing (or no longer showing) an alias in place of the bank id.
type SetBankAliasPrimaryRequest struct {
	// True to present the bank under this alias; False to go back to its own id.
	Primary bool `json:"primary"`
}

type _SetBankAliasPrimaryRequest SetBankAliasPrimaryRequest

// NewSetBankAliasPrimaryRequest instantiates a new SetBankAliasPrimaryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetBankAliasPrimaryRequest(primary bool) *SetBankAliasPrimaryRequest {
	this := SetBankAliasPrimaryRequest{}
	this.Primary = primary
	return &this
}

// NewSetBankAliasPrimaryRequestWithDefaults instantiates a new SetBankAliasPrimaryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetBankAliasPrimaryRequestWithDefaults() *SetBankAliasPrimaryRequest {
	this := SetBankAliasPrimaryRequest{}
	return &this
}

// GetPrimary returns the Primary field value
func (o *SetBankAliasPrimaryRequest) GetPrimary() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Primary
}

// GetPrimaryOk returns a tuple with the Primary field value
// and a boolean to check if the value has been set.
func (o *SetBankAliasPrimaryRequest) GetPrimaryOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Primary, true
}

// SetPrimary sets field value
func (o *SetBankAliasPrimaryRequest) SetPrimary(v bool) {
	o.Primary = v
}

func (o SetBankAliasPrimaryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetBankAliasPrimaryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["primary"] = o.Primary
	return toSerialize, nil
}

func (o *SetBankAliasPrimaryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"primary",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetBankAliasPrimaryRequest := _SetBankAliasPrimaryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetBankAliasPrimaryRequest)

	if err != nil {
		return err
	}

	*o = SetBankAliasPrimaryRequest(varSetBankAliasPrimaryRequest)

	return err
}

type NullableSetBankAliasPrimaryRequest struct {
	value *SetBankAliasPrimaryRequest
	isSet bool
}

func (v NullableSetBankAliasPrimaryRequest) Get() *SetBankAliasPrimaryRequest {
	return v.value
}

func (v *NullableSetBankAliasPrimaryRequest) Set(val *SetBankAliasPrimaryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetBankAliasPrimaryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetBankAliasPrimaryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetBankAliasPrimaryRequest(val *SetBankAliasPrimaryRequest) *NullableSetBankAliasPrimaryRequest {
	return &NullableSetBankAliasPrimaryRequest{value: val, isSet: true}
}

func (v NullableSetBankAliasPrimaryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetBankAliasPrimaryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


