/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the TemporalWindow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemporalWindow{}

// TemporalWindow A caller-supplied window for recall's temporal arm.  Supplying this **replaces the date extraction** recall would otherwise run over the query text, so a caller that already knows the range it means does not have to phrase it in English and hope the parser agrees.  It is **not a filter**. The temporal arm is one of four retrieval arms: it surfaces memories whose own dates (``mentioned_at`` / ``occurred_start`` / ``occurred_end``) fall inside the window so fusion can rank them higher. The semantic, keyword and graph arms are unaffected, so results dated outside the window are still returned. Narrowing results to a date range is a different operation this does not provide.  Has no effect when the bank's ``enable_temporal_retrieval`` config is off: that flag gates the arm itself, and stays the single switch for it.
type TemporalWindow struct {
	// Start of the window (inclusive).
	Start time.Time `json:"start"`
	// End of the window (inclusive).
	End time.Time `json:"end"`
}

type _TemporalWindow TemporalWindow

// NewTemporalWindow instantiates a new TemporalWindow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemporalWindow(start time.Time, end time.Time) *TemporalWindow {
	this := TemporalWindow{}
	this.Start = start
	this.End = end
	return &this
}

// NewTemporalWindowWithDefaults instantiates a new TemporalWindow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemporalWindowWithDefaults() *TemporalWindow {
	this := TemporalWindow{}
	return &this
}

// GetStart returns the Start field value
func (o *TemporalWindow) GetStart() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *TemporalWindow) GetStartOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *TemporalWindow) SetStart(v time.Time) {
	o.Start = v
}

// GetEnd returns the End field value
func (o *TemporalWindow) GetEnd() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.End
}

// GetEndOk returns a tuple with the End field value
// and a boolean to check if the value has been set.
func (o *TemporalWindow) GetEndOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.End, true
}

// SetEnd sets field value
func (o *TemporalWindow) SetEnd(v time.Time) {
	o.End = v
}

func (o TemporalWindow) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemporalWindow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["start"] = o.Start
	toSerialize["end"] = o.End
	return toSerialize, nil
}

func (o *TemporalWindow) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"start",
		"end",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemporalWindow := _TemporalWindow{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTemporalWindow)

	if err != nil {
		return err
	}

	*o = TemporalWindow(varTemporalWindow)

	return err
}

type NullableTemporalWindow struct {
	value *TemporalWindow
	isSet bool
}

func (v NullableTemporalWindow) Get() *TemporalWindow {
	return v.value
}

func (v *NullableTemporalWindow) Set(val *TemporalWindow) {
	v.value = val
	v.isSet = true
}

func (v NullableTemporalWindow) IsSet() bool {
	return v.isSet
}

func (v *NullableTemporalWindow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemporalWindow(val *TemporalWindow) *NullableTemporalWindow {
	return &NullableTemporalWindow{value: val, isSet: true}
}

func (v NullableTemporalWindow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemporalWindow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


