/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StrategyRulePreview type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StrategyRulePreview{}

// StrategyRulePreview What one rule (one entry of a strategy's `scopes`) matches among existing scopes.
type StrategyRulePreview struct {
	// Existing scopes this rule matches
	MatchCount int32 `json:"match_count"`
	// Of those, how many an earlier strategy wins, so this one has no effect
	TakenCount int32 `json:"taken_count"`
	// Observations across the matching scopes
	ObservationCount int32 `json:"observation_count"`
	// The most populous matching scopes, up to sample_limit
	Samples []StrategyScopePreview `json:"samples"`
}

type _StrategyRulePreview StrategyRulePreview

// NewStrategyRulePreview instantiates a new StrategyRulePreview object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStrategyRulePreview(matchCount int32, takenCount int32, observationCount int32, samples []StrategyScopePreview) *StrategyRulePreview {
	this := StrategyRulePreview{}
	this.MatchCount = matchCount
	this.TakenCount = takenCount
	this.ObservationCount = observationCount
	this.Samples = samples
	return &this
}

// NewStrategyRulePreviewWithDefaults instantiates a new StrategyRulePreview object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStrategyRulePreviewWithDefaults() *StrategyRulePreview {
	this := StrategyRulePreview{}
	return &this
}

// GetMatchCount returns the MatchCount field value
func (o *StrategyRulePreview) GetMatchCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MatchCount
}

// GetMatchCountOk returns a tuple with the MatchCount field value
// and a boolean to check if the value has been set.
func (o *StrategyRulePreview) GetMatchCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MatchCount, true
}

// SetMatchCount sets field value
func (o *StrategyRulePreview) SetMatchCount(v int32) {
	o.MatchCount = v
}

// GetTakenCount returns the TakenCount field value
func (o *StrategyRulePreview) GetTakenCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TakenCount
}

// GetTakenCountOk returns a tuple with the TakenCount field value
// and a boolean to check if the value has been set.
func (o *StrategyRulePreview) GetTakenCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TakenCount, true
}

// SetTakenCount sets field value
func (o *StrategyRulePreview) SetTakenCount(v int32) {
	o.TakenCount = v
}

// GetObservationCount returns the ObservationCount field value
func (o *StrategyRulePreview) GetObservationCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ObservationCount
}

// GetObservationCountOk returns a tuple with the ObservationCount field value
// and a boolean to check if the value has been set.
func (o *StrategyRulePreview) GetObservationCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObservationCount, true
}

// SetObservationCount sets field value
func (o *StrategyRulePreview) SetObservationCount(v int32) {
	o.ObservationCount = v
}

// GetSamples returns the Samples field value
func (o *StrategyRulePreview) GetSamples() []StrategyScopePreview {
	if o == nil {
		var ret []StrategyScopePreview
		return ret
	}

	return o.Samples
}

// GetSamplesOk returns a tuple with the Samples field value
// and a boolean to check if the value has been set.
func (o *StrategyRulePreview) GetSamplesOk() ([]StrategyScopePreview, bool) {
	if o == nil {
		return nil, false
	}
	return o.Samples, true
}

// SetSamples sets field value
func (o *StrategyRulePreview) SetSamples(v []StrategyScopePreview) {
	o.Samples = v
}

func (o StrategyRulePreview) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StrategyRulePreview) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["match_count"] = o.MatchCount
	toSerialize["taken_count"] = o.TakenCount
	toSerialize["observation_count"] = o.ObservationCount
	toSerialize["samples"] = o.Samples
	return toSerialize, nil
}

func (o *StrategyRulePreview) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"match_count",
		"taken_count",
		"observation_count",
		"samples",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStrategyRulePreview := _StrategyRulePreview{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStrategyRulePreview)

	if err != nil {
		return err
	}

	*o = StrategyRulePreview(varStrategyRulePreview)

	return err
}

type NullableStrategyRulePreview struct {
	value *StrategyRulePreview
	isSet bool
}

func (v NullableStrategyRulePreview) Get() *StrategyRulePreview {
	return v.value
}

func (v *NullableStrategyRulePreview) Set(val *StrategyRulePreview) {
	v.value = val
	v.isSet = true
}

func (v NullableStrategyRulePreview) IsSet() bool {
	return v.isSet
}

func (v *NullableStrategyRulePreview) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStrategyRulePreview(val *StrategyRulePreview) *NullableStrategyRulePreview {
	return &NullableStrategyRulePreview{value: val, isSet: true}
}

func (v NullableStrategyRulePreview) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStrategyRulePreview) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


