/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TextContentBlock type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TextContentBlock{}

// TextContentBlock A run of text within a multimodal item, in the position the caller wrote it.
type TextContentBlock struct {
	Type string `json:"type"`
	Text string `json:"text"`
}

type _TextContentBlock TextContentBlock

// NewTextContentBlock instantiates a new TextContentBlock object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTextContentBlock(type_ string, text string) *TextContentBlock {
	this := TextContentBlock{}
	this.Type = type_
	this.Text = text
	return &this
}

// NewTextContentBlockWithDefaults instantiates a new TextContentBlock object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTextContentBlockWithDefaults() *TextContentBlock {
	this := TextContentBlock{}
	return &this
}

// GetType returns the Type field value
func (o *TextContentBlock) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TextContentBlock) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TextContentBlock) SetType(v string) {
	o.Type = v
}

// GetText returns the Text field value
func (o *TextContentBlock) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *TextContentBlock) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *TextContentBlock) SetText(v string) {
	o.Text = v
}

func (o TextContentBlock) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TextContentBlock) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["text"] = o.Text
	return toSerialize, nil
}

func (o *TextContentBlock) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTextContentBlock := _TextContentBlock{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTextContentBlock)

	if err != nil {
		return err
	}

	*o = TextContentBlock(varTextContentBlock)

	return err
}

type NullableTextContentBlock struct {
	value *TextContentBlock
	isSet bool
}

func (v NullableTextContentBlock) Get() *TextContentBlock {
	return v.value
}

func (v *NullableTextContentBlock) Set(val *TextContentBlock) {
	v.value = val
	v.isSet = true
}

func (v NullableTextContentBlock) IsSet() bool {
	return v.isSet
}

func (v *NullableTextContentBlock) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTextContentBlock(val *TextContentBlock) *NullableTextContentBlock {
	return &NullableTextContentBlock{value: val, isSet: true}
}

func (v NullableTextContentBlock) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTextContentBlock) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


