/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MemoryGraphNodeData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemoryGraphNodeData{}

// MemoryGraphNodeData The payload of one memory-unit node in the memory graph.  Extra keys are allowed and passed through, so typing this never drops a field the server also returns.
type MemoryGraphNodeData struct {
	// Memory unit ID
	Id string `json:"id"`
	// Short display label (the text, truncated)
	Label *string `json:"label,omitempty"`
	// Full memory unit text
	Text *string `json:"text,omitempty"`
	// Event date (ISO 8601), empty when unknown
	Date *string `json:"date,omitempty"`
	// Context the memory was captured in
	Context *string `json:"context,omitempty"`
	// Comma-separated entity names, 'None' when there are none
	Entities *string `json:"entities,omitempty"`
	Color NullableString `json:"color,omitempty"`
}

type _MemoryGraphNodeData MemoryGraphNodeData

// NewMemoryGraphNodeData instantiates a new MemoryGraphNodeData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemoryGraphNodeData(id string) *MemoryGraphNodeData {
	this := MemoryGraphNodeData{}
	this.Id = id
	var label string = ""
	this.Label = &label
	var text string = ""
	this.Text = &text
	var date string = ""
	this.Date = &date
	var context string = ""
	this.Context = &context
	var entities string = ""
	this.Entities = &entities
	return &this
}

// NewMemoryGraphNodeDataWithDefaults instantiates a new MemoryGraphNodeData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemoryGraphNodeDataWithDefaults() *MemoryGraphNodeData {
	this := MemoryGraphNodeData{}
	var label string = ""
	this.Label = &label
	var text string = ""
	this.Text = &text
	var date string = ""
	this.Date = &date
	var context string = ""
	this.Context = &context
	var entities string = ""
	this.Entities = &entities
	return &this
}

// GetId returns the Id field value
func (o *MemoryGraphNodeData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MemoryGraphNodeData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MemoryGraphNodeData) SetId(v string) {
	o.Id = v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *MemoryGraphNodeData) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemoryGraphNodeData) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *MemoryGraphNodeData) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *MemoryGraphNodeData) SetLabel(v string) {
	o.Label = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *MemoryGraphNodeData) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemoryGraphNodeData) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *MemoryGraphNodeData) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *MemoryGraphNodeData) SetText(v string) {
	o.Text = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *MemoryGraphNodeData) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemoryGraphNodeData) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *MemoryGraphNodeData) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *MemoryGraphNodeData) SetDate(v string) {
	o.Date = &v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *MemoryGraphNodeData) GetContext() string {
	if o == nil || IsNil(o.Context) {
		var ret string
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemoryGraphNodeData) GetContextOk() (*string, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *MemoryGraphNodeData) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given string and assigns it to the Context field.
func (o *MemoryGraphNodeData) SetContext(v string) {
	o.Context = &v
}

// GetEntities returns the Entities field value if set, zero value otherwise.
func (o *MemoryGraphNodeData) GetEntities() string {
	if o == nil || IsNil(o.Entities) {
		var ret string
		return ret
	}
	return *o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemoryGraphNodeData) GetEntitiesOk() (*string, bool) {
	if o == nil || IsNil(o.Entities) {
		return nil, false
	}
	return o.Entities, true
}

// HasEntities returns a boolean if a field has been set.
func (o *MemoryGraphNodeData) HasEntities() bool {
	if o != nil && !IsNil(o.Entities) {
		return true
	}

	return false
}

// SetEntities gets a reference to the given string and assigns it to the Entities field.
func (o *MemoryGraphNodeData) SetEntities(v string) {
	o.Entities = &v
}

// GetColor returns the Color field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MemoryGraphNodeData) GetColor() string {
	if o == nil || IsNil(o.Color.Get()) {
		var ret string
		return ret
	}
	return *o.Color.Get()
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MemoryGraphNodeData) GetColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Color.Get(), o.Color.IsSet()
}

// HasColor returns a boolean if a field has been set.
func (o *MemoryGraphNodeData) HasColor() bool {
	if o != nil && o.Color.IsSet() {
		return true
	}

	return false
}

// SetColor gets a reference to the given NullableString and assigns it to the Color field.
func (o *MemoryGraphNodeData) SetColor(v string) {
	o.Color.Set(&v)
}
// SetColorNil sets the value for Color to be an explicit nil
func (o *MemoryGraphNodeData) SetColorNil() {
	o.Color.Set(nil)
}

// UnsetColor ensures that no value is present for Color, not even an explicit nil
func (o *MemoryGraphNodeData) UnsetColor() {
	o.Color.Unset()
}

func (o MemoryGraphNodeData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemoryGraphNodeData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.Entities) {
		toSerialize["entities"] = o.Entities
	}
	if o.Color.IsSet() {
		toSerialize["color"] = o.Color.Get()
	}
	return toSerialize, nil
}

func (o *MemoryGraphNodeData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemoryGraphNodeData := _MemoryGraphNodeData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMemoryGraphNodeData)

	if err != nil {
		return err
	}

	*o = MemoryGraphNodeData(varMemoryGraphNodeData)

	return err
}

type NullableMemoryGraphNodeData struct {
	value *MemoryGraphNodeData
	isSet bool
}

func (v NullableMemoryGraphNodeData) Get() *MemoryGraphNodeData {
	return v.value
}

func (v *NullableMemoryGraphNodeData) Set(val *MemoryGraphNodeData) {
	v.value = val
	v.isSet = true
}

func (v NullableMemoryGraphNodeData) IsSet() bool {
	return v.isSet
}

func (v *NullableMemoryGraphNodeData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemoryGraphNodeData(val *MemoryGraphNodeData) *NullableMemoryGraphNodeData {
	return &NullableMemoryGraphNodeData{value: val, isSet: true}
}

func (v NullableMemoryGraphNodeData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemoryGraphNodeData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


