/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PromptBlockModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PromptBlockModel{}

// PromptBlockModel One block of a message: its text, and the setting that decides it.  The **active** blocks of a message concatenate back to the exact text sent, so a client can render them separately without showing the reader something the model never receives. An **inactive** block has no text: it marks a setting that is switched off, at the point where it would land if it were on.  Everything identifying a block is a machine value, never display copy — what a block is called, and what turning a switched-off one on would do, is for the client to say in the language it is running in.
type PromptBlockModel struct {
	// The block's text; empty when the block is inactive.
	Text string `json:"text"`
	// `config` — produced by a setting (`field` names it); `builtin` — Hindsight's own wording.
	Source string `json:"source"`
	// Config field behind this block; empty when no single field owns it.
	Field *string `json:"field,omitempty"`
	// Slug for a part the preview names itself and no field owns: `bank_identity`, `disposition`, `directives`. Empty otherwise.
	Section *string `json:"section,omitempty"`
	// The section heading the prompt text carries at this point, extracted from the prompt itself. Empty when it carries none.
	Heading *string `json:"heading,omitempty"`
	// Whether this block is in the prompt as configured.
	Active *bool `json:"active,omitempty"`
	Value NullableString `json:"value,omitempty"`
	// Shape of the value, so a client can offer the right control for editing it.
	Kind string `json:"kind"`
	Choices []string `json:"choices,omitempty"`
	// Whether this bank may override the field via the bank config API. Server-level fields shape the prompt but cannot be set per bank, and offering to edit one would only collect a 400.
	Editable *bool `json:"editable,omitempty"`
}

type _PromptBlockModel PromptBlockModel

// NewPromptBlockModel instantiates a new PromptBlockModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromptBlockModel(text string, source string, kind string) *PromptBlockModel {
	this := PromptBlockModel{}
	this.Text = text
	this.Source = source
	var field string = ""
	this.Field = &field
	var section string = ""
	this.Section = &section
	var heading string = ""
	this.Heading = &heading
	var active bool = true
	this.Active = &active
	this.Kind = kind
	var editable bool = false
	this.Editable = &editable
	return &this
}

// NewPromptBlockModelWithDefaults instantiates a new PromptBlockModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromptBlockModelWithDefaults() *PromptBlockModel {
	this := PromptBlockModel{}
	var field string = ""
	this.Field = &field
	var section string = ""
	this.Section = &section
	var heading string = ""
	this.Heading = &heading
	var active bool = true
	this.Active = &active
	var editable bool = false
	this.Editable = &editable
	return &this
}

// GetText returns the Text field value
func (o *PromptBlockModel) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *PromptBlockModel) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *PromptBlockModel) SetText(v string) {
	o.Text = v
}

// GetSource returns the Source field value
func (o *PromptBlockModel) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *PromptBlockModel) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *PromptBlockModel) SetSource(v string) {
	o.Source = v
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *PromptBlockModel) GetField() string {
	if o == nil || IsNil(o.Field) {
		var ret string
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromptBlockModel) GetFieldOk() (*string, bool) {
	if o == nil || IsNil(o.Field) {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *PromptBlockModel) HasField() bool {
	if o != nil && !IsNil(o.Field) {
		return true
	}

	return false
}

// SetField gets a reference to the given string and assigns it to the Field field.
func (o *PromptBlockModel) SetField(v string) {
	o.Field = &v
}

// GetSection returns the Section field value if set, zero value otherwise.
func (o *PromptBlockModel) GetSection() string {
	if o == nil || IsNil(o.Section) {
		var ret string
		return ret
	}
	return *o.Section
}

// GetSectionOk returns a tuple with the Section field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromptBlockModel) GetSectionOk() (*string, bool) {
	if o == nil || IsNil(o.Section) {
		return nil, false
	}
	return o.Section, true
}

// HasSection returns a boolean if a field has been set.
func (o *PromptBlockModel) HasSection() bool {
	if o != nil && !IsNil(o.Section) {
		return true
	}

	return false
}

// SetSection gets a reference to the given string and assigns it to the Section field.
func (o *PromptBlockModel) SetSection(v string) {
	o.Section = &v
}

// GetHeading returns the Heading field value if set, zero value otherwise.
func (o *PromptBlockModel) GetHeading() string {
	if o == nil || IsNil(o.Heading) {
		var ret string
		return ret
	}
	return *o.Heading
}

// GetHeadingOk returns a tuple with the Heading field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromptBlockModel) GetHeadingOk() (*string, bool) {
	if o == nil || IsNil(o.Heading) {
		return nil, false
	}
	return o.Heading, true
}

// HasHeading returns a boolean if a field has been set.
func (o *PromptBlockModel) HasHeading() bool {
	if o != nil && !IsNil(o.Heading) {
		return true
	}

	return false
}

// SetHeading gets a reference to the given string and assigns it to the Heading field.
func (o *PromptBlockModel) SetHeading(v string) {
	o.Heading = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *PromptBlockModel) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromptBlockModel) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *PromptBlockModel) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *PromptBlockModel) SetActive(v bool) {
	o.Active = &v
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptBlockModel) GetValue() string {
	if o == nil || IsNil(o.Value.Get()) {
		var ret string
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptBlockModel) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *PromptBlockModel) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableString and assigns it to the Value field.
func (o *PromptBlockModel) SetValue(v string) {
	o.Value.Set(&v)
}
// SetValueNil sets the value for Value to be an explicit nil
func (o *PromptBlockModel) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *PromptBlockModel) UnsetValue() {
	o.Value.Unset()
}

// GetKind returns the Kind field value
func (o *PromptBlockModel) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *PromptBlockModel) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *PromptBlockModel) SetKind(v string) {
	o.Kind = v
}

// GetChoices returns the Choices field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PromptBlockModel) GetChoices() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Choices
}

// GetChoicesOk returns a tuple with the Choices field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptBlockModel) GetChoicesOk() ([]string, bool) {
	if o == nil || IsNil(o.Choices) {
		return nil, false
	}
	return o.Choices, true
}

// HasChoices returns a boolean if a field has been set.
func (o *PromptBlockModel) HasChoices() bool {
	if o != nil && !IsNil(o.Choices) {
		return true
	}

	return false
}

// SetChoices gets a reference to the given []string and assigns it to the Choices field.
func (o *PromptBlockModel) SetChoices(v []string) {
	o.Choices = v
}

// GetEditable returns the Editable field value if set, zero value otherwise.
func (o *PromptBlockModel) GetEditable() bool {
	if o == nil || IsNil(o.Editable) {
		var ret bool
		return ret
	}
	return *o.Editable
}

// GetEditableOk returns a tuple with the Editable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromptBlockModel) GetEditableOk() (*bool, bool) {
	if o == nil || IsNil(o.Editable) {
		return nil, false
	}
	return o.Editable, true
}

// HasEditable returns a boolean if a field has been set.
func (o *PromptBlockModel) HasEditable() bool {
	if o != nil && !IsNil(o.Editable) {
		return true
	}

	return false
}

// SetEditable gets a reference to the given bool and assigns it to the Editable field.
func (o *PromptBlockModel) SetEditable(v bool) {
	o.Editable = &v
}

func (o PromptBlockModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PromptBlockModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	toSerialize["source"] = o.Source
	if !IsNil(o.Field) {
		toSerialize["field"] = o.Field
	}
	if !IsNil(o.Section) {
		toSerialize["section"] = o.Section
	}
	if !IsNil(o.Heading) {
		toSerialize["heading"] = o.Heading
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if o.Value.IsSet() {
		toSerialize["value"] = o.Value.Get()
	}
	toSerialize["kind"] = o.Kind
	if o.Choices != nil {
		toSerialize["choices"] = o.Choices
	}
	if !IsNil(o.Editable) {
		toSerialize["editable"] = o.Editable
	}
	return toSerialize, nil
}

func (o *PromptBlockModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
		"source",
		"kind",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPromptBlockModel := _PromptBlockModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPromptBlockModel)

	if err != nil {
		return err
	}

	*o = PromptBlockModel(varPromptBlockModel)

	return err
}

type NullablePromptBlockModel struct {
	value *PromptBlockModel
	isSet bool
}

func (v NullablePromptBlockModel) Get() *PromptBlockModel {
	return v.value
}

func (v *NullablePromptBlockModel) Set(val *PromptBlockModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePromptBlockModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePromptBlockModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromptBlockModel(val *PromptBlockModel) *NullablePromptBlockModel {
	return &NullablePromptBlockModel{value: val, isSet: true}
}

func (v NullablePromptBlockModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromptBlockModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


