/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExtractionChunk type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExtractionChunk{}

// ExtractionChunk One chunk the extractor was handed, and how much it yielded.
type ExtractionChunk struct {
	// The chunk as the extractor saw it.
	Text string `json:"text"`
	// How many facts came out of this chunk.
	FactCount int32 `json:"fact_count"`
}

type _ExtractionChunk ExtractionChunk

// NewExtractionChunk instantiates a new ExtractionChunk object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExtractionChunk(text string, factCount int32) *ExtractionChunk {
	this := ExtractionChunk{}
	this.Text = text
	this.FactCount = factCount
	return &this
}

// NewExtractionChunkWithDefaults instantiates a new ExtractionChunk object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExtractionChunkWithDefaults() *ExtractionChunk {
	this := ExtractionChunk{}
	return &this
}

// GetText returns the Text field value
func (o *ExtractionChunk) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *ExtractionChunk) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *ExtractionChunk) SetText(v string) {
	o.Text = v
}

// GetFactCount returns the FactCount field value
func (o *ExtractionChunk) GetFactCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FactCount
}

// GetFactCountOk returns a tuple with the FactCount field value
// and a boolean to check if the value has been set.
func (o *ExtractionChunk) GetFactCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FactCount, true
}

// SetFactCount sets field value
func (o *ExtractionChunk) SetFactCount(v int32) {
	o.FactCount = v
}

func (o ExtractionChunk) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExtractionChunk) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	toSerialize["fact_count"] = o.FactCount
	return toSerialize, nil
}

func (o *ExtractionChunk) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
		"fact_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExtractionChunk := _ExtractionChunk{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExtractionChunk)

	if err != nil {
		return err
	}

	*o = ExtractionChunk(varExtractionChunk)

	return err
}

type NullableExtractionChunk struct {
	value *ExtractionChunk
	isSet bool
}

func (v NullableExtractionChunk) Get() *ExtractionChunk {
	return v.value
}

func (v *NullableExtractionChunk) Set(val *ExtractionChunk) {
	v.value = val
	v.isSet = true
}

func (v NullableExtractionChunk) IsSet() bool {
	return v.isSet
}

func (v *NullableExtractionChunk) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExtractionChunk(val *ExtractionChunk) *NullableExtractionChunk {
	return &NullableExtractionChunk{value: val, isSet: true}
}

func (v NullableExtractionChunk) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExtractionChunk) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


