/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateBankAliasRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBankAliasRequest{}

// CreateBankAliasRequest Request model for adding an alias to a bank.
type CreateBankAliasRequest struct {
	// The extra bank id. Same rules as a bank id (non-empty, at most 192 bytes of UTF-8, no control characters), and it must not already name a bank or another alias.
	Alias string `json:"alias"`
}

type _CreateBankAliasRequest CreateBankAliasRequest

// NewCreateBankAliasRequest instantiates a new CreateBankAliasRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBankAliasRequest(alias string) *CreateBankAliasRequest {
	this := CreateBankAliasRequest{}
	this.Alias = alias
	return &this
}

// NewCreateBankAliasRequestWithDefaults instantiates a new CreateBankAliasRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBankAliasRequestWithDefaults() *CreateBankAliasRequest {
	this := CreateBankAliasRequest{}
	return &this
}

// GetAlias returns the Alias field value
func (o *CreateBankAliasRequest) GetAlias() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Alias
}

// GetAliasOk returns a tuple with the Alias field value
// and a boolean to check if the value has been set.
func (o *CreateBankAliasRequest) GetAliasOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Alias, true
}

// SetAlias sets field value
func (o *CreateBankAliasRequest) SetAlias(v string) {
	o.Alias = v
}

func (o CreateBankAliasRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBankAliasRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["alias"] = o.Alias
	return toSerialize, nil
}

func (o *CreateBankAliasRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"alias",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateBankAliasRequest := _CreateBankAliasRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateBankAliasRequest)

	if err != nil {
		return err
	}

	*o = CreateBankAliasRequest(varCreateBankAliasRequest)

	return err
}

type NullableCreateBankAliasRequest struct {
	value *CreateBankAliasRequest
	isSet bool
}

func (v NullableCreateBankAliasRequest) Get() *CreateBankAliasRequest {
	return v.value
}

func (v *NullableCreateBankAliasRequest) Set(val *CreateBankAliasRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBankAliasRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBankAliasRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBankAliasRequest(val *CreateBankAliasRequest) *NullableCreateBankAliasRequest {
	return &NullableCreateBankAliasRequest{value: val, isSet: true}
}

func (v NullableCreateBankAliasRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBankAliasRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


